### ISSUE TITLE
2.1.0 Testing

### ISSUE THREAD

**Issue by ronalfy** [ronalfy/reorder-posts#15]
@ryanhellyer and @scottbasgaard 

If you guys have time, the 2.1.0 version here needs to be tested.

The main thing I added is pagination and the rippling of queries so we don't crash a server :)

@ryanhellyer I took your suggestion and adding some offsets with pagination so that you can move from page to page with the previous two items shown.

I've finished the main coding of my Reorder By Term plugin, but I don't expect you guys to test that out.

Please comment here or add an issue if you find anything.  Please turn debug on to catch any errors.

**Comment by ryanhellyer** [comment]
This version doesn't seem to be working unfortunately. I tried running it on my live site, but it won't reorder the posts now.

**Comment by ryanhellyer** [comment]
It's also adding some test saying "menu order:" followed by a number (presumably the menu order).

**Comment by ronalfy** [comment]
If debug is on, it shows the menu order.  I can turn this off if you want.

**Comment by ronalfy** [comment]
I'll do some more testing and see if I can duplicate.  Thanks Ryan.

**Comment by ronalfy** [comment]
Hey guys, I'm done with my reorder-by-terms plugin for the most part.  I'd like to get this update out so I can release the terms plugin on .org.  If you have time, please do a quick sanity test of this plugin.

**Comment by scottbasgaard** [comment]
@ronalfy looking through this now.

**Comment by scottbasgaard** [comment]
Looking good Ron :+1:

**Comment by ronalfy** [comment]
Thanks guys.
