### ISSUE TITLE
Reordering breaking on post save

### ISSUE THREAD

**Issue by ryanhellyer** [ronalfy/reorder-posts#16]
This page displays sub-pages of itself ... https://geek.hellyer.kiwi/plugins/

I can reorder those pages, and it works as expected. However, if I edit and re-save one of those pages, it automatically goes to the top, which I hadn't intended.

**Comment by ronalfy** [comment]
So to duplicate, create a query showing pages sorted by menu order, then re-save a page and see if it changes the order?

**Comment by ronalfy** [comment]
I couldn't duplicate this.  Are you sure you didn't already have the post open, re-ordered, then saved it again, thus reverting the order?

**Comment by scottbasgaard** [comment]
I'm having issues replicating this as well.

**Comment by ryanhellyer** [comment]
Sorry, I missed your questions here.

I tested the latest version and this bug seems to have been fixed now.
