### ISSUE TITLE
Add disclaimer on reorder page

### ISSUE THREAD

**Issue by ronalfy** [ronalfy/reorder-posts#18]
@scottbasgaard mentioned we should have some type of disclaimer on the reorder page or something that says, we do not override queries on the front-end.

**Comment by ryanhellyer** [comment]
But isn't that what your recent additions do?

**Comment by ronalfy** [comment]
I don't think I have a disclaimer.  I'll double-check.  My brain is a little fried at the moment :D

I'll probably also do what I do with the reorder-by-terms plugin and add an example of a custom query.

**Comment by ronalfy** [comment]
Oh, I see what you mean.  In the settings, you can manually adjust the query order.  I've actually contemplated removing this feature.

Competing plugins do indeed override the queries, but I don't want to go down that rabbit hole.  I see Reorder posts as a powerful and configurable reorder tool for developers, not necessarily the end user who has no idea what post types are or what WP_Query is.

**Comment by ryanhellyer** [comment]
This is a sign that I haven't properly looked at that stuff you added yet ;)
