### ISSUE TITLE
Remove strange error message

### ISSUE THREAD

**Issue by ryanhellyer** [ronalfy/reorder-posts#20]
A strange error message appeared on the reorder posts page in a recent update

https://wordpress.org/support/topic/option-to-remove-warning-note-on-reorder-page?replies=2#post-6493934

**Comment by ronalfy** [comment]
That's not a bug. It's just simply stating that reordering in the back end
doesn't affect the front end without some custom code.

**Comment by ryanhellyer** [comment]
In that case it is indeed a bug, because the reordering does affect the front-end. In fact I assume that's the only reason people use it. It's definitely the only reason I use it.

Are you perhaps trying to say that it doesn't affect the main blog loop?

**Comment by ronalfy** [comment]
It doesn't affect the front-end unless people use the menu_order property in their queries.

**Comment by ronalfy** [comment]
I'll just remove this in the next update.  The goal was to avoid negative reviews on .org.

**Comment by ryanhellyer** [comment]
I think a message is okay, but what it says now is just not true unfortunately.

**Comment by ronalfy** [comment]
It is true if someone blindly installs the plugin, reorders, and expects things to magically work in their theme without code mods.

Anyways, I removed it.  

https://github.com/ronalfy/reorder-posts/commit/b472cd06d271b6d0f2e7f851e496ca7042e43be1#diff-e64cd8935e880e684f2cd30aa4d1869e

**Comment by ryanhellyer** [comment]
I didn't make any code mods to my site when I started using the plugin. It just worked automatically.
