### ISSUE TITLE
Menu order isn't changing

### ISSUE THREAD

**Issue by ryanhellyer** [ronalfy/reorder-posts#22]
I'm modifying the order of a page, and it's working. But for some reason the page order is not changing??? Isn't that how it works? It modifies the page order?

**Comment by ronalfy** [comment]
Yeah, it changes the menu_order argument in the posts table.

**Comment by ryanhellyer** [comment]
... queue Twilight zone music ... 

The Emoji plugin shows a menu order of zero, yet is not the first in the list (the list is definitely controlled by the plugin).
https://geek.hellyer.kiwi/plugins/

![reorder](https://cloud.githubusercontent.com/assets/430544/6790927/893716b6-d1ab-11e4-98fd-480aa145c260.png)

**Comment by ronalfy** [comment]
Hmm, can you do me a favor and place a constant in your config

```php
define( 'REORDER_DEBUG', true );
```

Then on the Reorder it'll spit out what menu order everything is.

**Comment by ronalfy** [comment]
There might me multiple zeros is my concern.

**Comment by ryanhellyer** [comment]
Me no understandy ... 

![reorder](https://cloud.githubusercontent.com/assets/430544/6792900/b3b16466-d1bd-11e4-85a1-ba8d12e454f1.png)

**Comment by ronalfy** [comment]
Hmm, that is weird.  Does re-ordering help fix the order at all?

**Comment by ryanhellyer** [comment]
No. What you see above is after I reordered.

I just don't get how it's reordering it at all, if the menu order is not changing :/

**Comment by ryanhellyer** [comment]
The plugin does appear to be working. Just in a magical mystery way which I do not understand :/

**Comment by ryanhellyer** [comment]
I have a theory that this might be a caching issue. The plugin uses direct queries, but the menu orders may be stored in the object cache. So perhaps the cache is displaying those numbers, but you are pulling the order directly from the DB.

I'll test this later once I regain SSH access to my server (stupid connection keeps failing from my current location).

**Comment by ryanhellyer** [comment]
I got in faster than I thought. I disabled my object cache and the problem disappeared. So I'm guessing there is some cache which is meant to be flushed during the reordering process.

**Comment by ronalfy** [comment]
Yeah, if I did wp_update_post, which does some cache clearing, the
reordering process takes about 50 times longer. If you find a solution,
please let me know.

**Comment by ronalfy** [comment]
@ryanhellyer I added some cache-busting to version 2.1.4.  It should be working because it's the same thing done in wp_insert_post, but if you can try it out, you will help out with my sanity and I can close this :D

**Comment by ryanhellyer** [comment]
Working :)

**Comment by ryanhellyer** [comment]
Working :)
