### ISSUE TITLE
i have updated with the latest 'posts' update and have lost the filter menu facility. It is blank any ideas??

### ISSUE THREAD

**Issue by independent6** [ronalfy/reorder-posts#26]

**Comment by ronalfy** [comment]
Can you provide a screenshot and more details of what you saw before?

**Comment by independent6** [comment]
Hello

Thanks for the email. I have taken a screen shot of what we get now when we click on the drop down box. Before the update there were 4 or so options to choose from.

Regards

Justin

**Comment by ronalfy** [comment]
Still not seeing a screenshot sorry. You can just drag the file into the comment form and it'll upload and display here.

**Comment by independent6** [comment]
![img_6522](https://cloud.githubusercontent.com/assets/18459977/14524199/2bc8b498-022f-11e6-8e6b-377c37eb7d2a.JPG)

**Comment by ronalfy** [comment]
Thanks. I think you have the wrong plugin unfortunately. Our UI looks nothing like that.

**Comment by independent6** [comment]
thank you. I am not a pc wizz what is a UI?

**Comment by ronalfy** [comment]
Sorry! User Interface. Our plugin looks totally different. Not sure which one you are using.

**Comment by independent6** [comment]
ok thank you. I shall have my IT guys look at it. :)
